name: CI/CD Pipeline

on:
  #push:
  #  branches: [ main ]
  workflow_dispatch:  # Define the trigger for the workflow, manual execution in this case


jobs:
  build-and-deploy:
    runs-on: ubuntu-latest  # Use an Ubuntu-based runner for this job

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2   # Check out the code repository

    - name: Install Azure CLI
      run: |
        curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

    - name: Set up Azure credentials
      env:
        AZURE_CLIENT_ID: ${{ secrets.AZURE_SP_CLIENT_ID }}
        AZURE_CLIENT_SECRET: ${{ secrets.AZURE_SP_CLIENT_SECRET }}
        AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      run: |
        echo "AZURE_CREDENTIALS='{}'" > $GITHUB_ENV

    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Build Docker Image
      run: docker build -t aforero68/app-age:latest .  # Build the Docker image from the code

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}   # Log in to Docker Hub using secrets
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Push Image to Docker Hub
      run: docker push aforero68/app-age:latest  # Push the Docker image to Docker Hub

    - name: Deploy to Azure Container Instances
      run: |
        # Define Azure Container Instances (ACI) parameters
        aciName="magiclog-container"
        resourceGroup="magiclog"
        image="aforero68/app-age:latest" # Replace with your Docker image

        # Create an ACI container
        az container create --resource-group $resourceGroup --name $aciName --image $image --dns-name-label $aciName --ports 3000 --environment-variables KEY=VALUE

        # Wait for the container to be fully deployed
        az container wait --resource-group $resourceGroup --name $aciName --created
        az container wait --resource-group $resourceGroup --name $aciName --running
        echo "Deployment to Azure Container Instances has been completed."